version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/matchbook-sdk
    steps:
      - checkout
      - restore_cache:
          key: matchbook-sdk-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: matchbook-sdk-{{ checksum "pom.xml" }}
      - run: mvn install

      - store_test_results:
          path: target/surefire-reports
