version: 2.1
jobs:

  build-java8:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/matchbook-sdk
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: matchbook-sdk-{{ checksum "pom.xml" }}
      - run: mvn --fail-never dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: matchbook-sdk-{{ checksum "pom.xml" }}

      - run:
          name: Build Matchbook SDK on Java 8
          command: |
            mvn -s settings.xml clean verify
            mvn surefire-report:report-only

      - run:
          name: Publish coverage reports
          command: |
            wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')
            java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r matchbook-sdk-rest/target/site/jacoco/jacoco.xml

      - store_test_results:
          path: matchbook-sdk-rest/target/surefire-reports

      - store_artifacts:
          path: matchbook-sdk-rest/target/site
          destination: matchbook-sdk-rest/reports

  build-java11:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/matchbook-sdk
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Build Matchbook SDK on Java 11
          command: |
            mvn clean verify -Dmaven.compiler.source=11 -Dmaven.compiler.target=11

  maven-deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/matchbook-sdk
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: matchbook-sdk-{{ checksum "pom.xml" }}
      - run:
          name: maven deploy
          command: mvn -s settings.xml -DskipTests clean deploy

  publish-github-release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            export VERSION=$(cat ~/project/pom.xml | grep "^    <version>.*</version>$" | awk -F'[><]' '{print $3}')
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/project

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-java11
      - build-java8
      - maven-deploy:
          requires:
            - build-java8
            - build-java11
#          filters:
#            branches:
#              only: master



