version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/matchbook-sdk
    steps:
      - checkout
      - restore_cache:
          key: matchbook-sdk-{{ checksum "pom.xml" }}
      - run: mvn --fail-never dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: matchbook-sdk-{{ checksum "pom.xml" }}
      - run: mvn install
      - run: mvn surefire-report:report-only

      - store_test_results:
          path: matchbook-sdk-core/target/surefire-reports

      - store_artifacts:
          path: matchbook-sdk-core/target/site
          destination: matchbook-sdk-core/reports
